version: '3.7'

services:

    zrtc-server:
        container_name: zrtc-server
        build:
            context: ./server
            dockerfile: Dockerfile
        volumes:
            - './server:/server'
            - '/server/node_modules'
        ports:
            - 8000:8000
        environment:
            - CHOKIDAR_USEPOLLING=true

    zrtc-client:
        container_name: zrtc-client
        build:
            context: ./client
            dockerfile: Dockerfile
        volumes:
            - './client:/client'
            - '/client/node_modules'
        ports:
            - 3000:3000
        environment:
            - CHOKIDAR_USEPOLLING=true
