# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  checkout_code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: install client
        run: |
          cd ./client
          npm ci
        
  test_client:
    runs-on: ubuntu-latest
    steps:
        
      - name: test client
        run: |
          cd ./client
          npm test
        
#   build_client:
#     runs-on: ubuntu-latest
#     steps:
#     # Runs a single command using the runners shell
#     - name: Run a one-line script
#       run: echo Hello, world!

#     # Runs a set of commands using the runners shell
#     - name: Run a multi-line script
#       run: |
#         echo Add other actions to build,
#         echo test, and deploy your project.
