# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_and_test_client:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: install client
        run: |
          cd ./client
          npm ci
        
      - name: test client
        run: |
          cd ./client
          npm test

      - name: build client
        run: |
          cd ./client
          npm run build

  build_and_test_server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: install server
        run: |
          cd ./server
          npm ci

      - name: test server
        run: |
          cd ./server
          npm test

